# Generated by Django 3.2.12 on 2024-03-17 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, null=True, verbose_name='Project name')),
                ('due_in', models.CharField(max_length=50, verbose_name='Due date')),
                ('tasks_completed', models.IntegerField(verbose_name='Number of completed tasks')),
                ('countries', models.CharField(max_length=2000, verbose_name='Countries applicable for this form')),
                ('img', models.ImageField(upload_to='src.agency.form_images')),
                ('document', models.FileField(null=True, upload_to='src.agency.forms')),
            ],
        ),
    ]
