# Generated by Django 3.2.12 on 2024-03-17 22:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, null=True, verbose_name='Project name')),
                ('created_at', models.CharField(max_length=50, null=True, verbose_name='Created at date')),
                ('due_in', models.CharField(max_length=50, verbose_name='Due date')),
                ('tasks_completed', models.IntegerField(verbose_name='Number of completed tasks')),
                ('tasks', models.IntegerField(null=True)),
            ],
        ),
    ]
