# Generated by Django 3.2.12 on 2024-03-17 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='tasks',
            field=models.IntegerField(null=True),
        ),
    ]
