# Generated by Django 3.2.12 on 2024-03-17 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_manager', '0002_project_tasks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='countries',
        ),
        migrations.RemoveField(
            model_name='project',
            name='document',
        ),
        migrations.RemoveField(
            model_name='project',
            name='img',
        ),
    ]
